"""
{{project_name}} - {{description}}

{{#if framework}}
Framework: {{framework}}
{{/if}}
Type: {{project_type}}
Generated by AI Project Template
"""

__version__ = "{{version}}"
__author__ = "{{author_name}}"
__email__ = "{{author_email}}"

{{#if framework}}
{{#if (eq framework "fastapi")}}
from .app import create_app

__all__ = ["create_app", "__version__"]
{{/if}}
{{#if (eq framework "flask")}}
from .app import create_app

__all__ = ["create_app", "__version__"]
{{/if}}
{{#if (eq framework "django")}}
# Django app - see settings.py for configuration
__all__ = ["__version__"]
{{/if}}
{{#if (eq framework "none")}}
from .main import main

__all__ = ["main", "__version__"]
{{/if}}
{{else}}
from .main import main

__all__ = ["main", "__version__"]
{{/if}}